proxmox_api_host: "192.168.0.21"
proxmox_api_user: "root@pam"
proxmox_api_password: "{{ vault_proxmox_api_password }}"
cluster_name: "pve-home"
proxmox_node: "pve-bijok01"
iso_storage: "isos"
storage: "datastore01"
vm_name: "opensuse-cloudinit"
vmid: "206"
static_ip: "192.168.1.204/24"
gateway: "192.168.1.1"
dns: "192.168.0.2"