proxmox_api_host: "192.168.0.21"
proxmox_api_user: "root@pam"
proxmox_api_password: "{{ vault_proxmox_api_password }}"
cluster_name: "pve-home"
iso_storage: "isos"
storage: "datastore01"
vm_name: "opensuse-cloudinit"
vmid: "100"
